### ISSUE TITLE
Caffeine 3.0 updates

### ISSUE THREAD

**Issue by ben-manes** [tydhot/CaffeineChineseWiki#6]
Hi @tydhot,

Caffeine 3.0 has finally landed! There were some minor updates to the wiki to correspond to that. It might be easiest to look at the git history, but I'll try to summarize them. I'd appreciate it if you could please update the translation.

- Home: Switched link from `Writer` to `Compute`
- Compute: Added (based on `Writer`)
- Removal: Updated from `CacheWriter` to `Caffeine.evictionListener`; updated from j.u.l. to Platform Logger
- Refresh: Updated from j.u.l. to Platform Logger
- Statistics: Updated to official Dropwizard adapter
- Specification: Removed "in 2.8.7"
- Policy: Update `Time-based`
- Writer: removed wiki page
- Roadmap: Rewrote
- Contribute: Removed outdated Eclipse plugins

Thanks!

**Comment by tydhot** [comment]
@ben-manes I'd love to do it :)!

**Comment by tydhot** [comment]
@ben-manes hi! I have finished it! :)

**Comment by ben-manes** [comment]
very nice, thank you! 🙂
